<?php

use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\Exception\LogicException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class YsGroupsCacheContainer extends Container
{
    protected $parameters = [];

    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->methodMap = [
            'YsGroups\\Controller\\Admin\\Admin' => 'getAdminService',
            'YsGroups\\Controller\\Front\\Front' => 'getFrontService',
            'YsGroups\\Services\\FixSomeErrors' => 'getFixSomeErrorsService',
            'YsGroups\\Services\\Mailer' => 'getMailerService',
            'YsGroups\\Services\\NotLoggedInRedirections' => 'getNotLoggedInRedirectionsService',
            'YsGroups\\Services\\RestApi' => 'getRestApiService',
            'YsGroups\\Services\\RewriteRules' => 'getRewriteRulesService',
            'YsGroups\\Services\\Session' => 'getSessionService',
        ];

        $this->aliases = [];
    }

    public function compile(): void
    {
        throw new LogicException('You cannot compile a dumped container that was already compiled.');
    }

    public function isCompiled(): bool
    {
        return true;
    }

    public function getRemovedIds(): array
    {
        return [
            'Psr\\Container\\ContainerInterface' => true,
            'Symfony\\Component\\DependencyInjection\\ContainerInterface' => true,
            'YsGroups\\Container' => true,
            'YsGroups\\Controller\\Admin\\AdminGroups' => true,
            'YsGroups\\Controller\\Admin\\GroupListTable' => true,
            'YsGroups\\Controller\\Admin\\Metaboxs\\PostMetas\\CoverPhotoMetaBox' => true,
            'YsGroups\\Controller\\Admin\\Metaboxs\\PostMetas\\GroupAdminMetabox' => true,
            'YsGroups\\Controller\\Admin\\Metaboxs\\PostMetas\\StatusMetaBox' => true,
            'YsGroups\\Controller\\Admin\\Metaboxs\\PostMetas\\GroupIdMetaBox' => true,
            'YsGroups\\Controller\\Admin\\Metaboxs\\TermMetas\\YsGroupsMemberTermMeta' => true,
            'YsGroups\\Controller\\Admin\\YsGroupCPT' => true,
            'YsGroups\\Controller\\Admin\\YsGroupPostCPT' => true,
            'YsGroups\\Controller\\Api\\YsGroupCreatedResponse' => true,
            'YsGroups\\Controller\\Api\\YsGroupNotFoundError' => true,
            'YsGroups\\Controller\\Api\\YsGroupOkResponse' => true,
            'YsGroups\\Controller\\Api\\YsGroupPostRestController' => true,
            'YsGroups\\Controller\\Api\\YsGroupRestApiSubscriber' => true,
            'YsGroups\\Controller\\Api\\YsGroupsRestEndpointInterface' => true,
            'YsGroups\\Controller\\Front\\GroupPostsController' => true,
            'YsGroups\\Controller\\Front\\GroupsController' => true,
            'YsGroups\\Helpers\\Helpers' => true,
            'YsGroups\\Model\\Db' => true,
            'YsGroups\\Model\\DbSchema' => true,
            'YsGroups\\Model\\Groups' => true,
            'YsGroups\\Model\\GroupsMembers' => true,
            'YsGroups\\Model\\GroupsPosts' => true,
            'YsGroups\\Model\\PluginPosts' => true,
            'YsGroups\\OnPluginActivation' => true,
            'YsGroups\\YsGroups' => true,
        ];
    }

    /**
     * Gets the public 'YsGroups\Controller\Admin\Admin' shared autowired service.
     *
     * @return \YsGroups\Controller\Admin\Admin
     */
    protected function getAdminService()
    {
        return $this->services['YsGroups\\Controller\\Admin\\Admin'] = new \YsGroups\Controller\Admin\Admin(
            new \YsGroups\Controller\Admin\AdminGroups(),
            new \YsGroups\Controller\Admin\YsGroupCPT(),
            new \YsGroups\Controller\Admin\Metaboxs\PostMetas\StatusMetaBox(),
            new \YsGroups\Controller\Admin\Metaboxs\PostMetas\GroupAdminMetabox(),
            new \YsGroups\Controller\Admin\Metaboxs\PostMetas\CoverPhotoMetaBox(),
            new \YsGroups\Controller\Admin\YsGroupPostCPT(),
            new \YsGroups\Controller\Admin\Metaboxs\PostMetas\GroupIdMetaBox(),
            new \YsGroups\Controller\Admin\Metaboxs\TermMetas\YsGroupsMemberTermMeta()
        );
    }

    /**
     * Gets the public 'YsGroups\Controller\Front\Front' shared autowired service.
     *
     * @return \YsGroups\Controller\Front\Front
     */
    protected function getFrontService()
    {
        return $this->services['YsGroups\\Controller\\Front\\Front'] = new \YsGroups\Controller\Front\Front(
            new \YsGroups\Controller\Front\GroupsController()
        );
    }

    /**
     * Gets the public 'YsGroups\Services\FixSomeErrors' shared autowired service.
     *
     * @return \YsGroups\Services\FixSomeErrors
     */
    protected function getFixSomeErrorsService()
    {
        return $this->services['YsGroups\\Services\\FixSomeErrors'] = new \YsGroups\Services\FixSomeErrors();
    }

    /**
     * Gets the public 'YsGroups\Services\Mailer' shared autowired service.
     *
     * @return \YsGroups\Services\Mailer
     */
    protected function getMailerService()
    {
        return $this->services['YsGroups\\Services\\Mailer'] = new \YsGroups\Services\Mailer();
    }

    /**
     * Gets the public 'YsGroups\Services\NotLoggedInRedirections' shared autowired service.
     *
     * @return \YsGroups\Services\NotLoggedInRedirections
     */
    protected function getNotLoggedInRedirectionsService()
    {
        return $this->services['YsGroups\\Services\\NotLoggedInRedirections'] = new \YsGroups\Services\NotLoggedInRedirections();
    }

    /**
     * Gets the public 'YsGroups\Services\RestApi' shared autowired service.
     *
     * @return \YsGroups\Services\RestApi
     */
    protected function getRestApiService()
    {
        return $this->services['YsGroups\\Services\\RestApi'] = new \YsGroups\Services\RestApi(
            new \YsGroups\Controller\Api\YsGroupPostRestController()
        );
    }

    /**
     * Gets the public 'YsGroups\Services\RewriteRules' shared autowired service.
     *
     * @return \YsGroups\Services\RewriteRules
     */
    protected function getRewriteRulesService()
    {
        return $this->services['YsGroups\\Services\\RewriteRules'] = new \YsGroups\Services\RewriteRules();
    }

    /**
     * Gets the public 'YsGroups\Services\Session' shared autowired service.
     *
     * @return \YsGroups\Services\Session
     */
    protected function getSessionService()
    {
        return $this->services['YsGroups\\Services\\Session'] = new \YsGroups\Services\Session();
    }
}
